### ISSUE TITLE
Missing libamdhip64.so for test_py_3.6_gpu_async on sles

### ISSUE THREAD

**Issue by ahsan-ca** [ROCmSoftwarePlatform/AMDMIGraphX#2263]
`test_py_3.6_gpu_async` fails on sles with the following error output:
```
Traceback (most recent call last):
  File "/code/AMDMIGraphX/AMDMIGraphX/test/py/test_gpu_async.py", line 74, in <module>
    test_conv_relu()
  File "/code/AMDMIGraphX/AMDMIGraphX/test/py/test_gpu_async.py", line 29, in test_conv_relu
    hip = ctypes.cdll.LoadLibrary("libamdhip64.so")
  File "/usr/lib64/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib64/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libamdhip64.so: cannot open shared object file: No such file or directory
```
**OS Version:**
NAME="SLES"
VERSION="15-SP4"
VERSION_ID="15.4"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP4"

**Python Version:**
Python 3.6.15

**Comment by ahsan-ca** [comment]
The failing test case `test_py_3.6_gpu_async` complains about a missing shared library `libamdhip64.so`.
This library can be found at `/opt/rocm/lib` on sles. In `/etc/ld.so.conf.d/rocm.conf`, I see `/opt/rocm/lib` being specified.

Also, in `/etc/ld.so.conf` we have:
```
/usr/local/lib64
/usr/local/lib
include /etc/ld.so.conf.d/*.conf
```
It should pick up the library but not sure why it is not picking that up. I was able to make the test case pass by specifying the full path to the library in the test case. 

Discussed this with Paul and he suggested to use full path for loading the library if the library exists at that path.

**Comment by ahsan-ca** [comment]
Got feedback on the [PR](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/pull/2264) to also check for the existence of `/opt/rocm-*` paths. Will look into adding that.

**Comment by ahsan-ca** [comment]
Modified the PR to check for paths in the order below:
1. `rocm_path` env variable.
2. `/opt/rocm`.
3. `/opt/rocm-*`
It is ready for review: https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/pull/2264
