### ISSUE TITLE
ONNX files mobilenet v1 and v2 fail at Opset 11

### ISSUE THREAD

**Issue by mvermeulen** [ROCmSoftwarePlatform/AMDMIGraphX#439]
Mobilenet v1 and v2 fail for Opset 11 but pass for Opset 10.  The following error is given:
```
  what():  /home/mev/source/AMDMIGraphX/src/include/migraphx/check_shapes.hpp:58
: Wrong number of arguments: expected 1 but given 3
```
The gdb stack trace for this error and a dump of the ONNX file contents suggest perhaps the "clip" operator may be the issue.  Here are parts of the gdb stack trace
```
#5  0x00007ffff539e775 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x0000000000457e12 in migraphx::version_1::check_shapes::has<int> (this=this@entry=0x7fffffff21c0)
    at /home/mev/source/AMDMIGraphX-debug/src/include/migraphx/check_shapes.hpp:57
#7  0x000000000045c174 in migraphx::version_1::op::unary<migraphx::version_1::op::sigmoid>::compute_shape (this=<optimized out>, 
    inputs=std::vector of length 3, capacity 3 = {...}) at /home/mev/source/AMDMIGraphX-debug/src/include/migraphx/op/unary.hpp:15
#8  0x00007ffff6a16131 in migraphx::version_1::operation::private_detail_te_handle_type<migraphx::version_1::op::clip>::compute_shape (
    this=0x866370, input=...) at /home/mev/source/AMDMIGraphX-debug/src/include/migraphx/operation.hpp:554
#9  0x00007ffff58e22ce in migraphx::version_1::operation::compute_shape (input=std::vector of length 3, capacity 3 = {...}, 
    this=0x7fffffff2410) at /home/mev/source/AMDMIGraphX-debug/src/include/migraphx/operation.hpp:338
#10 migraphx::version_1::compute_shape (op=..., args=std::vector of length 3, capacity 3 = {...})
    at /home/mev/source/AMDMIGraphX-debug/src/instruction.cpp:234
#11 0x00007ffff58e8581 in migraphx::version_1::program::insert_instruction (this=this@entry=0x7fffffffd100, ins=..., op=..., 
    args=std::vector of length 3, capacity 3 = {...}) at /home/mev/source/AMDMIGraphX-debug/src/program.cpp:169
#12 0x00007ffff58e88a3 in migraphx::version_1::program::add_instruction (this=this@entry=0x7fffffffd100, op=..., 
    args=std::vector of length 0, capacity 0) at /home/mev/source/AMDMIGraphX-debug/src/program.cpp:159
#13 0x00007ffff693cc2c in migraphx::version_1::onnx_parser::parse_clip (this=0x7fffffffd090, Python Exception <class 'IndexError'> list index out of range: 
attributes=std::unordered_map with 0 elements, 
    args=std::vector of length 0, capacity 0) at /home/mev/source/AMDMIGraphX-debug/src/onnx/onnx.cpp:317
#14 0x00007ffff68851bf in std::_Mem_fn_base<std::_List_iterator<migraphx::version_1::instruction> (migraphx::version_1::onnx_parser::*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, onnx::AttributeProto, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, onnx::AttributeProto> > > const&, std::vector<std::_List_iterator<migraphx::version_1::instruction>, std::allocator<std::_List_iterator<migraphx::version_1::instruction> > >), true>::operator()<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, onnx::AttributeProto, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, onnx::AttributeProto> > >, std::vector<std::_List_iterator<migraphx::version_1::instruction>, std::allocator<std::_List_iterator<migraphx::version_1::instruction> > >, void> (__object=..., this=<optimized out>)
    at /usr/include/c++/5/functional:583
```
Here is a comparison of the clip operator for Opset 10
```
{
        op    : Clip
        input : MobilenetV1/MobilenetV1/Conv2d_0/BatchNorm/FusedBatchNorm:0
        output: MobilenetV1/MobilenetV1/Conv2d_0/Relu6:0
        min: 0
        max: 6
}
```
In contrast, here is Opset 11
```
{
        op    : Clip
        input : MobilenetV1/MobilenetV1/Conv2d_0/BatchNorm/FusedBatchNorm:0 Mob\
ilenetV1/MobilenetV1/Conv2d_6_pointwise/Relu6_min__146 MobilenetV1/MobilenetV1/\
Conv2d_6_depthwise/Relu6_max__137
        output: MobilenetV1/MobilenetV1/Conv2d_0/Relu6:0
}
```

**Comment by scxiao** [comment]
This is because clip specification is changed to accept three arguments from opset10. For the three arguments, the second and third one are the max and min values, which are attributes in our implementation. If the second and third arguments are can be computed statically, we are still able to support that.
